"""
Django settings for jobportalapp project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-$!o!vsj621l!qlrl79)-7ugfk7sdch1y%5x&pi3ltg*$fsrb+2'

DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = "jobs.User"

import cloudinary.api
cloudinary.config(
    cloud_name='dlo2e1goo',
    api_key='824172995696766',
    api_secret='DH7-axX5kkk3fUdCQNsMmxy4V4U'
)

CKEDITOR_UPLOAD_PATH = 'images/ckeditors/'

INTERNAL_IPS = [
'127.0.0.1'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

# Application definition

INSTALLED_APPS = [
    'jobs.apps.JobsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary',
    'ckeditor',
    'ckeditor_uploader',
    'drf_yasg',
    'rest_framework',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'oauth2_provider',
    'django_extensions'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'jobportalapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobportalapp.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'jobportaldb',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = 'static/'

CLIENT_ID='sAlOJlY4I6znBv8I02YUOGEnB3BgbHfjM8v2702b'
CLIENT_SECRET='Tm9mRyYIRcKvTq5YVu35TLG6HWKMTkX9OzY6j54V8QuaHHjUBhBPkA2UdEAHuZj816bDmg4V3v5Bez0jCy9Zd83Ky1M8KjZy6IW0RvxiFzoY1pnDcRaPONDjXLQPDLbq'
