# Generated by Django 6.0.3 on 2026-04-20 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='savedjob',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='active',
            new_name='is_active',
        ),
    ]
