# Generated by Django 6.0.3 on 2026-04-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='is_negotiable',
            field=models.BooleanField(default=False, help_text='Lương thoả thuận'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.PositiveIntegerField(blank=True, help_text='Mức lương cao nhất (VNĐ)', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.PositiveIntegerField(blank=True, help_text='Mức lương thấp nhất (VNĐ)', null=True),
        ),
    ]
